### ISSUE TITLE
查看重复的modid时崩溃

### ISSUE THREAD

**Issue by MorningMC** [Coloryr/ColorMC#25]
崩溃报告:
```
Version:A32.20241109
System:Os:Windows Arch:x86_64
SystemName:Microsoft Windows 10.0.22631
Gui Crash
System.NullReferenceException: Object reference not set to an instance of an object.
   at ColorMC.Gui.UI.Model.GameEdit.GameEditModel.LoadMod1() in E:\code\ColorMC\src\ColorMC.Gui\UI\Model\GameEdit\GameEditTab4Model.cs:line 501
   at ColorMC.Gui.UI.Model.GameEdit.GameEditModel.set_ModText(String value) in E:\code\ColorMC\src\ColorMC.Gui\obj\Release\net8.0\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\ColorMC.Gui.UI.Model.GameEdit.GameEditModel.g.cs:line 1266
   at ColorMC.Gui.UI.Model.GameEdit.GameEditModel.DisplayMod(List`1 list) in E:\code\ColorMC\src\ColorMC.Gui\UI\Model\GameEdit\GameEditTab4Model.cs:line 362
   at ColorMC.Gui.UI.Model.GameEdit.GameEditModel.LoadMods() in E:\code\ColorMC\src\ColorMC.Gui\UI\Model\GameEdit\GameEditTab4Model.cs:line 399
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at ColorMC.Gui.ColorMCGui.Main(String[] args) in E:\code\ColorMC\src\ColorMC.Gui\ColorMCGui.cs:line 100
```
_我记得我几分钟前才提交的一个崩溃来着_

**Comment by MorningMC** [comment]
color幸苦了,帮忙修修bug

**Comment by Coloryr** [comment]
这个已经修了，在A33
