### ISSUE TITLE
实例名字可以输入非法路径字符，或粘贴多行内容以致启动器报错

### ISSUE THREAD

**Issue by Myitian** [Coloryr/ColorMC#6]
添加游戏实例时实例名字可以输入非法路径字符，或粘贴多行内容以致启动器报错
比如
```
[2023/9/27 19:20:20][Error]Gui Crash
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (文件名、目录名或卷标语法不正确。 : 'C:\minecraft\Launcher\ColorMC\minecraft\instances\CCDD
AABB')
 ---> System.IO.IOException: 文件名、目录名或卷标语法不正确。 : 'C:\minecraft\Launcher\ColorMC\minecraft\instances\CCDD
AABB'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at ColorMC.Core.LaunchPath.InstancesPath.CreateGame(GameSettingObj game)
   at ColorMC.Gui.UIBinding.GameBinding.AddGame(String name, String version, Loaders loaders, String loaderversion, String group)
   at ColorMC.Gui.UI.Model.Add.AddGame.AddGameModel.AddGame()
   --- End of inner exception stack trace ---
```
或者
```
[2023/9/27 19:23:45][Error]Gui Crash
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (文件名、目录名或卷标语法不正确。 : 'C:\minecraft\Launcher\ColorMC\minecraft\instances\***:::<<<>>>|||\')
 ---> System.IO.IOException: 文件名、目录名或卷标语法不正确。 : 'C:\minecraft\Launcher\ColorMC\minecraft\instances\***:::<<<>>>|||\'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at ColorMC.Core.LaunchPath.InstancesPath.CreateGame(GameSettingObj game)
   at ColorMC.Gui.UIBinding.GameBinding.AddGame(String name, String version, Loaders loaders, String loaderversion, String group)
   at ColorMC.Gui.UI.Model.Add.AddGame.AddGameModel.AddGame()
   --- End of inner exception stack trace ---
```

**Comment by Myitian** [comment]
非法文件名字符也会出错，
```csharp
Path.GetInvalidPathChars()
```
只提供了非法路径字符，非法文件名字符如`*`，`<`，`>`，`|`，`?`之类包含在
```csharp
Path.GetInvalidFileNameChars()
```
